spring:
  datasource:
    url: jdbc:postgresql://192.168.1.162:5432/postgres
    username: postgres
    password: '0000'
    driver-class-name: org.postgresql.Driver
  thymeleaf:    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    
password-crypt-key : myFirstPasswordEncoding
    
mybatis:  type-aliases-package: org.zerok.*
  configuration:    map-underscore-to-camel-case: true
  mapper-locations:  - classpath:org.zerok.mapper.**.xml